export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 3000,
  },
  {
    name: "Mar",
    "Active User": 5000,
  },
  {
    name: "Apr",
    "Active User": 4000,
  },
  {
    name: "May",
    "Active User": 3000,
  },
  {
    name: "Jun",
    "Active User": 2000,
  },
  {
    name: "Jul",
    "Active User": 4000,
  },
  {
    name: "Agu",
    "Active User": 3000,
  },
  {
    name: "Sep",
    "Active User": 4000,
  },
  {
    name: "Oct",
    "Active User": 1000,
  },
  {
    name: "Nov",
    "Active User": 4000,
  },
  {
    name: "Dec",
    "Active User": 3000,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 3000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];

export const userRows = [
  {
    id: 1,
    avatar: "https://robohash.org/odiodolorvoluptatem.png?size=50x50&set=set1",
    username: "Gae Wingate",
    email: "gwingate0@intel.com",
    isAdmin: true,
    createdAt: "07/01/2011",
    updatedAt: "30/04/2014",
  },
  {
    id: 2,
    avatar: "https://robohash.org/occaecaticommodiquia.png?size=50x50&set=set1",
    username: "Janek Tapenden",
    email: "jtapenden1@behance.net",
    isAdmin: true,
    createdAt: "21/02/2019",
    updatedAt: "17/11/2021",
  },
  {
    id: 3,
    avatar: "https://robohash.org/eositaqueet.png?size=50x50&set=set1",
    username: "Falkner Heather",
    email: "fheather2@time.com",
    isAdmin: false,
    createdAt: "13/05/2013",
    updatedAt: "08/11/2015",
  },
  {
    id: 4,
    avatar: "https://robohash.org/expeditamollitiaeos.png?size=50x50&set=set1",
    username: "Allx Renyard",
    email: "arenyard3@google.co.jp",
    isAdmin: false,
    createdAt: "11/11/2011",
    updatedAt: "18/03/2013",
  },
  {
    id: 5,
    avatar: "https://robohash.org/nostrumverosit.png?size=50x50&set=set1",
    username: "Nanette Yarnley",
    email: "nyarnley4@mtv.com",
    isAdmin: false,
    createdAt: "10/07/2020",
    updatedAt: "14/10/2010",
  },
  {
    id: 6,
    avatar: "https://robohash.org/maioresodioinventore.png?size=50x50&set=set1",
    username: "Montague Henric",
    email: "mhenric5@scribd.com",
    isAdmin: true,
    createdAt: "20/01/2013",
    updatedAt: "14/02/2011",
  },
  {
    id: 7,
    avatar:
      "https://robohash.org/suntarchitectorecusandae.png?size=50x50&set=set1",
    username: "Ardella Creaser",
    email: "acreaser6@artisteer.com",
    isAdmin: false,
    createdAt: "09/04/2015",
    updatedAt: "19/02/2015",
  },
  {
    id: 8,
    avatar: "https://robohash.org/quiautsit.png?size=50x50&set=set1",
    username: "Dev Ord",
    email: "dord7@amazon.co.jp",
    isAdmin: true,
    createdAt: "09/12/2016",
    updatedAt: "19/07/2009",
  },
  {
    id: 9,
    avatar: "https://robohash.org/porroautet.png?size=50x50&set=set1",
    username: "Suzette Matiebe",
    email: "smatiebe8@nps.gov",
    isAdmin: true,
    createdAt: "29/03/2021",
    updatedAt: "07/09/2018",
  },
  {
    id: 10,
    avatar: "https://robohash.org/dolorcorporisea.png?size=50x50&set=set1",
    username: "Georgeanna Larne",
    email: "glarne9@sciencedaily.com",
    isAdmin: false,
    createdAt: "26/12/2012",
    updatedAt: "05/05/2021",
  },
];

export const movieRows = [
  {
    id: 1,
    title: "Creature from the Haunted Sea",
    desc: "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    image: "http://dummyimage.com/1188x648.png/ff4444/ffffff",
    imageTitle: "http://dummyimage.com/433x403.png/5fa2dd/ffffff",
    imageSmall: "http://dummyimage.com/410x436.png/ff4444/ffffff",
    trailer: null,
    video: null,
    year: 2004,
    duration: "2h",
    genre: "Comedy|Horror",
    isSeries: true,
    views: 48989,
    likes: [{}, {}, {}],
    comments: [],
    createdAt: "05/06/2012",
    updatedAt: "04/12/2015",
  },
  {
    id: 2,
    title: "Man, Woman and Beast (L'uomo la donna e la bestia)",
    desc: "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",
    image: "http://dummyimage.com/1039x684.png/5fa2dd/ffffff",
    imageTitle: "http://dummyimage.com/587x456.png/dddddd/000000",
    imageSmall: "http://dummyimage.com/356x576.png/dddddd/000000",
    trailer: null,
    video: null,
    year: 1995,
    duration: "1h",
    genre: "Drama|Fantasy",
    isSeries: false,
    views: 42991,
    likes: [{}, {}, {}, {}],
    comments: [],
    createdAt: "23/03/2013",
    updatedAt: "24/07/2019",
  },
  {
    id: 3,
    title: "Ernest Film Festival, The",
    desc: "Nullam porttitor lacus at turpis.",
    image: "http://dummyimage.com/1033x681.png/cc0000/ffffff",
    imageTitle: "http://dummyimage.com/584x466.png/dddddd/000000",
    imageSmall: "http://dummyimage.com/325x598.png/dddddd/000000",
    trailer: null,
    video: null,
    year: 1993,
    duration: "2h30",
    genre: "Comedy",
    isSeries: true,
    views: 98392,
    likes: [],
    comments: [{}],
    createdAt: "12/07/2012",
    updatedAt: "19/01/2017",
  },
  {
    id: 4,
    title: "My Life as a Dog (Mitt liv som hund)",
    desc: "Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    image: "http://dummyimage.com/1193x730.png/dddddd/000000",
    imageTitle: "http://dummyimage.com/431x517.png/5fa2dd/ffffff",
    imageSmall: "http://dummyimage.com/525x456.png/cc0000/ffffff",
    trailer: null,
    video: null,
    year: 2010,
    duration: "3h",
    genre: "Comedy|Drama",
    isSeries: true,
    views: 78615,
    likes: [{}, {}, {}, {}, {}],
    comments: [],
    createdAt: "29/02/2012",
    updatedAt: "13/07/2015",
  },
  {
    id: 5,
    title: "Topaz",
    desc: "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
    image: "http://dummyimage.com/1022x518.png/dddddd/000000",
    imageTitle: "http://dummyimage.com/513x548.png/cc0000/ffffff",
    imageSmall: "http://dummyimage.com/320x498.png/ff4444/ffffff",
    trailer: null,
    video: null,
    year: 2004,
    duration: "2h",
    genre: "Thriller",
    isSeries: false,
    views: 14488,
    likes: [{}, {}, {}],
    comments: [{}, {}, {}, {}],
    createdAt: "09/09/2013",
    updatedAt: "18/06/2021",
  },
  {
    id: 6,
    title: "Finding Normal",
    desc: "Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    image: "http://dummyimage.com/1345x703.png/dddddd/000000",
    imageTitle: "http://dummyimage.com/471x521.png/cc0000/ffffff",
    imageSmall: "http://dummyimage.com/596x517.png/dddddd/000000",
    trailer: null,
    video: null,
    year: 2004,
    duration: "1h",
    genre: "Comedy|Romance",
    isSeries: true,
    views: 9321,
    likes: [{}],
    comments: [{}, {}],
    createdAt: "10/10/2011",
    updatedAt: "03/05/2021",
  },
  {
    id: 7,
    title: "It's Impossible to Learn to Plow by Reading Books",
    desc: "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
    image: "http://dummyimage.com/1329x562.png/ff4444/ffffff",
    imageTitle: "http://dummyimage.com/515x587.png/5fa2dd/ffffff",
    imageSmall: "http://dummyimage.com/361x392.png/5fa2dd/ffffff",
    trailer: null,
    video: null,
    year: 1989,
    duration: "3h",
    genre: "Drama",
    isSeries: true,
    views: 38307,
    likes: [{}, {}],
    comments: [{}],
    createdAt: "04/01/2013",
    updatedAt: "22/05/2015",
  },
  {
    id: 8,
    title: "Ten Seconds to Hell",
    desc: "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.",
    image: "http://dummyimage.com/1250x621.png/5fa2dd/ffffff",
    imageTitle: "http://dummyimage.com/453x488.png/5fa2dd/ffffff",
    imageSmall: "http://dummyimage.com/560x490.png/ff4444/ffffff",
    trailer: null,
    video: null,
    year: 2007,
    duration: "2h",
    genre: "Action|Drama|Romance|War",
    isSeries: true,
    views: 11018,
    likes: [{}, {}],
    comments: [{}, {}, {}, {}, {}],
    createdAt: "09/09/2011",
    updatedAt: "25/05/2016",
  },
  {
    id: 9,
    title: "Conquest",
    desc: "Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.",
    image: "http://dummyimage.com/1238x569.png/dddddd/000000",
    imageTitle: "http://dummyimage.com/524x543.png/dddddd/000000",
    imageSmall: "http://dummyimage.com/386x520.png/5fa2dd/ffffff",
    trailer: null,
    video: null,
    year: 2001,
    duration: "1h30",
    genre: "Action|Adventure|Fantasy",
    isSeries: true,
    views: 12012,
    likes: [],
    comments: [{}, {}, {}, {}, {}],
    createdAt: "14/02/2011",
    updatedAt: "22/12/2014",
  },
  {
    id: 10,
    title: "Transcendence",
    desc: "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    image: "http://dummyimage.com/1298x609.png/cc0000/ffffff",
    imageTitle: "http://dummyimage.com/408x430.png/ff4444/ffffff",
    imageSmall: "http://dummyimage.com/598x380.png/5fa2dd/ffffff",
    trailer: null,
    video: null,
    year: 1998,
    duration: "1h",
    genre: "Drama|Sci-Fi|IMAX",
    isSeries: true,
    views: 73302,
    likes: [],
    comments: [{}],
    createdAt: "22/10/2011",
    updatedAt: "24/02/2015",
  },
];

export const seriesRows = [
  {
    id: 1,
    title: "Loosies",
    genre: "Comedy|Drama|Romance",
    content: [{}],
    createdAt: "11/01/2010",
    updatedAt: "11/7/2021",
  },
  {
    id: 2,
    title: "Secretariat",
    genre: "Adventure|Drama",
    content: [{}, {}, {}, {}],
    createdAt: "03/07/2010",
    updatedAt: "9/22/2017",
  },
  {
    id: 3,
    title: "Small Faces",
    genre: "Drama",
    content: [{}, {}, {}, {}],
    createdAt: "12/08/2010",
    updatedAt: "11/20/2020",
  },
  {
    id: 4,
    title: "Dead Ringer",
    genre: "Drama|Thriller",
    content: [{}, {}, {}, {}, {}],
    createdAt: "09/08/2010",
    updatedAt: "1/5/2020",
  },
  {
    id: 5,
    title: "Scars of Dracula",
    genre: "Horror",
    content: [{}, {}, {}, {}],
    createdAt: "14/09/2010",
    updatedAt: "3/11/2014",
  },
  {
    id: 6,
    title: "Ways to Live Forever",
    genre: "Children|Drama",
    content: [{}, {}, {}],
    createdAt: "26/01/2010",
    updatedAt: "1/3/2013",
  },
  {
    id: 7,
    title: "John Wick",
    genre: "Action|Thriller",
    content: [{}, {}, {}, {}, {}],
    createdAt: "21/06/2010",
    updatedAt: "4/11/2012",
  },
  {
    id: 8,
    title: "Social Genocide (Memoria del saqueo)",
    genre: "Documentary",
    content: [{}, {}],
    createdAt: "09/12/2009",
    updatedAt: "6/26/2013",
  },
  {
    id: 9,
    title: "Assembly (Ji jie hao) ",
    genre: "Action|Drama|War",
    content: [{}],
    createdAt: "06/04/2010",
    updatedAt: "10/20/2013",
  },
  {
    id: 10,
    title: "Irma la Douce",
    genre: "Comedy",
    content: [{}, {}, {}, {}],
    createdAt: "10/02/2009",
    updatedAt: "8/20/2017",
  },
];
